server:
  port: 8080
  mode: debug # debug, release, test

database:
  host: localhost
  port: 5432
  user: arulkarim
  password: root
  name: todo_db
  sslmode: disable
  timezone: Asia/Jakarta

jwt:
  secret: "your-super-secret-key-change-in-production"
  expiry_hour: 24

